output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: false

pycodestyle:
  disable:
    - E501

pylint:
  disable:
    - line-too-long
    - consider-using-with
    - logging-fstring-interpolation
    - simplifiable-if-statement
    - broad-except
    - unspecified-encoding

pydocstyle:
  disable:
    - D203
    - D212
    - D213
    - D404
    - D107
    - D105
    - D401
    - D415
